defaultAirflowRepository: tiendat2807/airflow
defaultAirflowTag: "3.1.0"
airflowVersion: "3.1.0"

executor: KubernetesExecutor

data:
  metadataConnection:
    user: airflow
    pass: airflow
    protocol: postgresql
    host: postgres-postgresql-hl.catalog.svc.cluster.local
    port: 5432
    db: airflow
    sslmode: disable

webserverSecretKey: 'Y3dUUkZmNEdHS1prM29zam8zbDdwejlhUG5sVlVXTkw='

ingress:
  web:
    enabled: false
    ingressClassName: nginx
    path: "/" 
    pathType: Prefix
    host: airflow.local
    hosts:
      - airflow.local

users:
  createUserJob:
    enabled: true
    username: admin
    password: admin
    role: Admin
    email: admin@example.com
    firstName: admin
    lastName: user

dags:
  gitSync:
    enabled: true
    repo: https://github.com/tiendat07/data-platform-kubenetes.git
    branch: main
    rev: HEAD
    depth: 1
    subPath: "airflow"

extraEnv: |
  - name: AIRFLOW__CORE__DAGS_FOLDER
    value: '/opt/airflow/dags/repo/airflow/dags'
  - name: AIRFLOW__CORE__DEFAULT_TIMEZONE
    value: 'Asia/Ho_Chi_Minh'
  - name: AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT
    value: '300'
  - name: AIRFLOW__SCHEDULER__PARSING_CLEANUP_INTERVAL
    value: '30'

postgresql:
  enabled: false
redis:
  enabled: false
migrations:
  enabled: true