defaultAirflowRepository: tiendat2807/airflow
defaultAirflowTag: "3.1.0"
airflowVersion: "3.1.0"

executor: KubernetesExecutor

images:
  airflow:
    repository: tiendat2807/airflow
    tag: "3.1.0"
    pullPolicy: Always

data:
  metadataConnection:
    user: airflow
    pass: airflow
    protocol: postgresql
    # host: postgres-postgresql-hl.catalog.svc.cluster.local
    host: 192.168.1.110
    port: 5432
    db: airflow
    sslmode: disable

webserverSecretKey: 'Y3dUUkZmNEdHS1prM29zam8zbDdwejlhUG5sVlVXTkw='

users:
  createUserJob:
    enabled: true
    username: admin
    password: admin
    role: Admin
    email: admin@example.com
    firstName: admin
    lastName: user

dags:
  gitSync:
    enabled: true
    repo: https://github.com/tiendat07/data-platform-kubenetes.git
    branch: main
    rev: HEAD
    depth: 1
    subPath: "airflow"

config:
  core:
    load_examples: 'True'
  logging:
    remote_logging: 'True'
    remote_base_log_folder: 's3://airflow/logs'
    remote_log_conn_id: 's3_default'
    encryption: 'False'

dependencies:
  - name: apache-airflow-providers-cncf-kubernetes
    version: 10.9.0

extraEnv: |
  - name: AIRFLOW__CORE__DAGS_FOLDER
    value: '/opt/airflow/dags/repo/airflow/dags'
  - name: AIRFLOW__CORE__DEFAULT_TIMEZONE
    value: 'Asia/Ho_Chi_Minh'
  - name: AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT
    value: '300'
  - name: AIRFLOW__SCHEDULER__PARSING_CLEANUP_INTERVAL
    value: '30'
  - name: AWS_ACCESS_KEY_ID
    value: 'admin'
  - name: AWS_SECRET_ACCESS_KEY
    value: 'password'
  - name: AWS_ENDPOINT_URL
    value: 'http://192.168.1.111:9000'

postgresql:
  enabled: false
redis:
  enabled: false
migrations:
  enabled: true