---
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-iceberg
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "tiendat2807/spark-lakehouse:0.0.9"
  imagePullPolicy: Always
  mainApplicationFile: local:///app/etl/main_iceberg.py
  sparkVersion: "3.5.6"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    memory: "1024m"
    labels:
      version: 3.5.6
    serviceAccount: spark
    env:
      - name: AWS_REGION
        value: us-east-1
      - name: AWS_ACCESS_KEY_ID
        value: admin
      - name: AWS_SECRET_ACCESS_KEY
        value: password
      - name: S3_ENDPOINT
        value: minio.minio.svc.cluster.local:9000
      - name: S3_SSL_ENABLE
        value: "false"
      - name: S3_PATH_STYLE_ACCESS
        value: "true"
      - name: S3_WAREHOUSE
        value: "s3a://lakehouse/"
      - name: ICEBERG_REST_CATALOG_URI
        value: "http://iceberg-rest-catalog.catalog.svc.cluster.local:8181"
      - name: DATA_PATH
        value: "s3a://raw/tripdata/"
        
  executor:
    cores: 1
    instances: 3
    memory: "2048m"
    labels:
      version: 3.5.6
    env:
      - name: AWS_REGION
        value: us-east-1
      - name: AWS_ACCESS_KEY_ID
        value: admin
      - name: AWS_SECRET_ACCESS_KEY
        value: password
      - name: S3_ENDPOINT
        value: minio.minio.svc.cluster.local:9000
      - name: S3_SSL_ENABLE
        value: "false"
      - name: S3_PATH_STYLE_ACCESS
        value: "true"
      - name: S3_WAREHOUSE
        value: "s3a://lakehouse/"
      - name: ICEBERG_REST_CATALOG_URI
        value: "http://iceberg-rest-catalog.catalog.svc.cluster.local:8181"
      - name: DATA_PATH
        value: "s3a://raw/tripdata/"