# spark-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: spark-role
rules:
- apiGroups: [""] # The empty "" indicates the core API group
  resources: ["pods", "services", "configmaps", "events", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "delete", "deletecollection", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: spark # This binds the role to your 'spark' ServiceAccount
  namespace: default
roleRef:
  kind: Role
  name: spark-role # This refers to the Role defined above
  apiGroup: rbac.authorization.k8s.io
