apiVersion: v1
kind: Service
metadata:
  name: iceberg-rest-catalog
  namespace: catalog
spec:
  ports:
  - name: http
    port: 8181
    targetPort: 8181
  selector:
    app: iceberg-rest-catalog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iceberg-rest-catalog
  namespace: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iceberg-rest-catalog
  template:
    metadata:
      labels:
        app: iceberg-rest-catalog
    spec:
      containers:
      - name: catalog
        image: tabulario/iceberg-rest:1.6.0
        ports:
        - containerPort: 8181
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: CATALOG_IO__IMPL
          value: "org.apache.iceberg.aws.s3.S3FileIO"
        - name: CATALOG_WAREHOUSE
          value: "s3://lakehouse/"
        - name: CATALOG_URI
          value: "jdbc:postgresql://postgres-postgresql-hl.catalog.svc.cluster.local:5432/iceberg_catalog"
        - name: CATALOG_JDBC_USER
          value: "iceberg"
        - name: CATALOG_JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-postgresql
              key: password
        - name: CATALOG_S3_PATH-STYLE-ACCESS
          value: "true"
        - name: CATALOG_S3_ENDPOINT
          value: "http://minio.minio.svc.cluster.local:9000"
        - name: AWS_ACCESS_KEY_ID
          value: "admin"
        - name: AWS_SECRET_ACCESS_KEY
          value: "password"
        - name: AWS_REGION
          value: "us-east-1"

