server:
  workers: 2

coordinator:
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 2
      memory: 4Gi
  service:
    type: ClusterIP
    port: 8080

additionalConfigProperties:
  - http-server.process-forwarded=true

additionalCatalogs:
  lakehouse: |
    connector.name=iceberg
    iceberg.catalog.type=rest
    iceberg.rest-catalog.uri=http://iceberg-rest-catalog.catalog.svc.cluster.local:8181
    iceberg.rest-catalog.warehouse=s3://lakehouse/
    iceberg.file-format=PARQUET
    fs.native-s3.enabled=true
    s3.path-style-access=true
    s3.endpoint=http://minio.minio.svc.cluster.local:9000
    s3.aws-access-key=admin
    s3.aws-secret-key=password
    s3.region=us-east-1
    iceberg.register-table-procedure.enabled=true
    iceberg.unique-table-location=true
