apiVersion: v1
kind: Namespace
metadata:
  name: sparglim
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparglim-server
  namespace: sparglim
  labels:
    app: sparglim-server
spec:
  replicas: 1

  selector:
    matchLabels:
      app: sparglim-server
  template:
    metadata:
      labels:
        app: sparglim-server
    spec:
      serviceAccountName: spark
      containers:
        - name: sparglim-server
          image: tiendat2807/sparglim-server
          ports:
            - containerPort: 15002
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          env:
            - name: SPARGLIM_SERVER_MODE
              value: "k8s"
            - name: SPARGLIM_DRIVER_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SPARGLIM_DRIVER_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SPARGLIM_SERVER_CUSTOM_CONFIG
              # json string for custom config, see https://spark.apache.org/docs/latest/configuration.html
              value: |
                {
                  "spark.dynamicAllocation.enabled": "true",
                  "spark.dynamicAllocation.shuffleTracking.enabled": "true",
                  "spark.dynamicAllocation.shuffleTracking.timeout": "180s",
                  "spark.dynamicAllocation.executorIdleTimeout": "60s",
                  "spark.dynamicAllocation.cachedExecutorIdleTimeout": "120s"
                }
            - name: AWS_ACCESS_KEY_ID
              value: "admin"
            - name: AWS_SECRET_ACCESS_KEY
              value: "password"
            - name: S3_ENTRY_POINT
              # value: "minio.minio.svc.cluster.local:9000"
              value: "192.168.1.111:9000"
            - name: S3_HTTP_ENTRY_POINT
              # value: "http://minio.minio.svc.cluster.local:9000"
              value: "http://192.168.1.111:9000"
            - name: S3_PATH_STYLE_ACCESS
              value: "true"
            - name: SPARGLIM_K8S_IMAGE
              value: "tiendat2807/spark-iceberg:0.0.3"
            - name: SPARGLIM_K8S_IMAGE_PULL_POLICY
              value: "Always"
            - name: SPARK_EXECUTOR_NUMS
              value: "2"  # Initial/minimum executors
            - name: SPARGLIM_DYNAMIC_ALLOCATION_ENABLED
              value: "true"
            - name: SPARGLIM_DYNAMIC_ALLOCATION_MIN_EXECUTORS
              value: "0"  # Can scale down to 0 (save resources when idle)
            - name: SPARGLIM_DYNAMIC_ALLOCATION_MAX_EXECUTORS
              value: "7"  # Can scale up to 10 (handle large workloads)
            - name: SPARGLIM_DYNAMIC_ALLOCATION_INITIAL_EXECUTORS
              value: "2"  # Start with 2
            - name: SPARGLIM_EXECUTOR_REQUEST_MEMORY
              value: "2G"
            - name: SPARGLIM_EXECUTOR_LIMIT_MEMORY
              value: "2G"
            - name: SPARGLIM_K8S_EXECUTOR_REQUEST_CORES
              value: "3"
            - name: SPARGLIM_EXECUTOR_CORES
              value: "3"
            - name: SPARGLIM_K8S_EXECUTOR_LIMIT_CORES
              value: "3"
            - name: SPARGLIM_SQL_CATALOG_LAKEHOUSE_WAREHOUSE
              value: "s3a://lakehouse/"
            - name: SPARGLIM_SQL_CATALOG_LAKEHOUSE_TYPE
              value: "rest"
            - name: SPARGLIM_SQL_CATALOG_LAKEHOUSE_URI
              # value: "http://iceberg-rest-catalog.catalog.svc.cluster.local:8181"
              value: "http://192.168.1.111:8181"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            - name: AWS_REGION
              value: "us-east-1"
            - name: S3_SSL_ENABLE
              value: "false"
