apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
spec:
  restartPolicy: Never
  runtimeClassName: nvidia
  nodeSelector:
    accelerator: nvidia
    kubernetes.io/hostname: dao-tien-dat
  containers:
  - name: cuda
    image: nvidia/cuda:12.2.0-runtime-ubuntu22.04   # ← runtime or devel
    command: ["nvidia-smi"]
    resources:
      limits:
        nvidia.com/gpu: 1