version: "3"
services:
  postgres:
    image: postgres:18
    container_name: postgres
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: iceberg
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iceberg_catalog
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iceberg -d iceberg_catalog"]
      interval: 5s
      timeout: 5s
      retries: 5